### ISSUE TITLE
[Enhancement] Change Utils Md5Hash function

### ISSUE THREAD

**Issue by Artuvanu** [xamarin/Essentials#1026]
## Summary
Replace md5Hash with a more secure function

## API Changes

- https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Types/Shared/Utils.shared.cs
    - Line 23-36

## Intended Use Case
Reduced vulnerability

**Comment by mattleibow** [comment]
Just a not for all would be changes... This is used in the key for look-ups in the `SecureStorage`, so changes mush either have a fallback or we might have to decide on a better way to make this change.

**Comment by jamesmontemagno** [comment]
It is just a hash of the key, which isn't sensitive data and the md5hash isn't used on any sensitive data. @Redth can comment on implementation. 

Changing this would be a breaking change most likely.

**Comment by Redth** [comment]
This is something we need to do to support FIPS mode on windows potentially however it’s not truly a security concern for as James mentioned it is simply used to hash the keys to obtain a predictable length and range of values for the key. It’s not used to securely hash anything. 

The problem is we need some sort of migration strategy which is very difficult to automatically do since we have no way to infer the existing key original values. Basically we would need developers to opt into the migration themselves. 

One idea I’ve been considering is a setting to enable a strict mode where we never use the md5 APIs. Without this mode enabled we can certainly do some automatic migration to sha256 as values are saved/updated but still fall back on looking up existing values by md5 key hash if the sha256 key hash key doesn’t exist. In strict mode we would simply omit the fallback to the md5 key check as to not invoke the API at runtime.

**Comment by Mrnikbobjeff** [comment]
@Redth This is exactly the way to go IMHO. The fallback needs to exist, but as a default I would suggest only using Sha1, as this is the only available hashing algorithm in the bcl which is also fips compliant. BouncyCastle has algorithms for newer hashing algorithms as well, but pulling in a dependency just for that is overkill. Also, AFAIK DataManager is also not FIPS compliant, which would mean a rework of the uwp encryption in general.

**Comment by mattleibow** [comment]
This was updated and now only exists in the Android version of the `Preferences` for backwards compatibility,
