### ISSUE TITLE
[Bug] DeviceInfo.Idiom return TV instead of Phone while Xamarin.Forms.Device.Idiom return idiom correct

### ISSUE THREAD

**Issue by kcrg** [xamarin/Essentials#1027]
### Description
Returns inconsistent values from Forms and Essentials.

### Steps to Reproduce
1. Compare returns values from Xamarin.Essentials.DeviceInfo.Idiom and Xamarin.Forms.Device.Idiom on Xiaomi Mi9 SE

### Expected Behavior
Xamarin.Forms.Device.Idiom and Xamarin.Essentials.DeviceInfo.Idiom behave in same way.

### Actual Behavior
Xamarin.Forms.Device.Idiom returns TargetIdiom.Phone
Xamarin.Essentials.DeviceInfo.Idiom returns DeviceIdiom.TV

### Basic Information

- Version with issue: 1.3.1
- Last known good version: null
- IDE: Visual Studio 2019 16.4
- Platform Target Frameworks:
  - Android: 9.0, stable MIUI Global 11.0.4.0
- Affected Devices: Xiaomi Mi9 SE

### Screenshots
I have modified Sample Xamarin.Essentials project to compare Essentials to Forms.
![Screenshot_2019-12-17-19-18-09-718_com xamarin essentials](https://user-images.githubusercontent.com/7996711/71024199-b0527080-2104-11ea-818f-7667947a296f.jpg)

### Additional Information
My device return CurrentModeType = 12 which means CurrentModeType.HasFlag(UiMode.TypeTelevision); will returns true.
![1](https://user-images.githubusercontent.com/7996711/71024368-0e7f5380-2105-11ea-8cc1-20f4b6f1f11f.PNG)

**Comment by jamesmontemagno** [comment]
Seems like this is a bug in the phone ourselves. Not sure if there is anything we can do based on your screenshot. https://stackoverflow.com/questions/27138838/how-can-i-check-if-an-app-is-running-on-an-android-tv

Technically we could check if there is a touchscreen..... that may be the fix.

**Comment by jamesmontemagno** [comment]
Actually, i think instead of "hasflag" it needs to be a direct comparison

**Comment by jamesmontemagno** [comment]
I believe that device is outputting that it is multiple things: https://docs.microsoft.com/en-us/dotnet/api/android.content.res.uimode?view=xamarin-android-sdk-9 as you can see here Television's enum is 4

Can you see what other types it is reporting that it is?

**Comment by jamesmontemagno** [comment]
Our code is actually identical:
https://github.com/xamarin/Xamarin.Forms/blob/190dda803621cb61a2d93834cdbddae2bac3c777/Xamarin.Forms.Platform.Android/Forms.cs#L355
and 
https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs#L82

**Comment by jamesmontemagno** [comment]
oh nm, i found it.

**Comment by PawKanarek** [comment]
I think that checking enum UiMode with HasFlag is wrong. We should check it using Equals() or == https://docs.microsoft.com/en-us/dotnet/api/android.content.res.uimode?view=xamarin-android-sdk-9. I made simple app to prove my point. For example: Checking UIMode = 6 (Watch) will give you true on TypeDesk, TypeTelevision, TypeWatch, NightUndefined and TypeUndefined. 

![image](https://user-images.githubusercontent.com/15096514/71077442-b50c3880-2187-11ea-9be0-482381da600f.png)


Checking for UIMode from this issue 12(some Xiaomi wierd phone) will give you true on TypeTelevision and  NightUndefined and TypeUndefined.

![image](https://user-images.githubusercontent.com/15096514/71077543-e8e75e00-2187-11ea-91a3-531483e6cafd.png)

We should change checking enum from HasFlag() to equality check, that will give us unequivocal results. That should be also fixed in Xamarin.Forms code.

**Comment by PawKanarek** [comment]
From what i tested most all my phones are type 1, TypeNormal
