### ISSUE TITLE
[Enhancement] Make available all SigningWithApple properties in WebAuthenticationResult when using AppleAuthenticator

### ISSUE THREAD

**Issue by magoolation** [xamarin/Essentials#1253]
### Description

When using AppleAuthenticator we don't have access to AuthenticationCode and State that are necessary to validate an refresh tokens with Apple.necessary 

### Steps to Reproduce

1. Create a new Xamarin.Forms app
2. Call AppleAuthenticator.AuthenticateAsync()
3. It'll return id_token but not the other properties

### Expected Behavior

AuthenticationCode and State should be present in Properties dictionary.

### Actual Behavior

Properties has only id_token.

### Basic Information

- Version with issue:1.5.3.1
- Last known good version:N/A
- IDE:Visual Studio 2019 16.5
- Platform Target Frameworks: 
  - iOS:13.4  

- Affected Devices:
Tested on iPhone XS

**Comment by richp582** [comment]
Yep, I ran into this too and had to fork the code into my own service to pull auth code out and return it... would be nice for OOTB support

**Comment by newky2k** [comment]
@richp582 @magoolation I'll review the pull request that was submitted, i can see that it has failed i'll i get back to you

**Comment by ncosentino** [comment]
I was about to open a new issue but I feel like this is related enough to what I'm interested in. Apologies if not, I'm happy to open something else. But my situation is as follows:

- Using Xamarin Essentials sign in with Apple
- Prompt for permission comes up perfectly... enter the pincode and it works perfectly
- I get an auth response with an id_token which is what I need for my next step...
- Firebase! I make an Apple credential for Firebase using:
```
OAuthProvider.GetCredential("apple.com", idToken, null);
```
- Firebase allows this and everything is AWESOME
- Except this token expires after like an hour or so (maybe it's 30 minutes? I can't recall) and then I have no way to refresh the authentication at all.
- If I resubmit the id_token to firebase to authenticate with, it tells me the credential has already been used (which is of course true).

I'm making an assumption here, but my hope would be that if there's more fields for the SignInWithApple result then I'd be able to get a nonce and/or a refresh_token to do some stuff with. Otherwise, I feel like I need to re-prompt the user to login and that feels pretty terrible.

Again, if this is unrelated I'll spin up another issue. Fingers are crossed this would allow me to do what I want because it's *so* close to working except for refreshing tokens.

**Comment by richp582** [comment]
My understanding is when you use the sign in with apple native experience you get the id token, you can then call apple and exchange the id token for an access token which does nothing and a refresh token, which is what you want.

**Comment by mattleibow** [comment]
Fixed in #1254

**Comment by Kapusch** [comment]
> But my situation is as follows:
> * Using Xamarin Essentials sign in with Apple
> * Prompt for permission comes up perfectly... enter the pincode and it works perfectly
> * I get an auth response with an id_token which is what I need for my next step...
> * Firebase! I make an Apple credential for Firebase using:
> 
> ```
> OAuthProvider.GetCredential("apple.com", idToken, null);
> ```
> 
> * Firebase allows this and everything is AWESOME

Hello @ncosentino ,

I'm currently struggling with "Apple Sign In" integration into my XF app.
I understand from your comment that you were able to combine Xamarin.Essentials Apple Sign In along with Firebase.

Could you please tell from which library did you get this "OAuthProvider" ?
