### ISSUE TITLE
[Bug] Cannot login to Google Account with WebAuthenticator on Android

### ISSUE THREAD

**Issue by tipa** [xamarin/Essentials#1256]
### Description
When I try to use the WebAuthenticator to login to my Google Account and Android is showing the login prompt (see screenshot below) the auth flow cannot be completed

### Steps to Reproduce
--> see repo project attached
(use a browser with no cached Google login credentials to reproduce the issue)

### Expected Behavior
User can complete auth flow and `code` is being returned to caller

### Actual Behavior
After clicking on "Yes" on the login prompt, the "OnResume" method of my activity is being called and the auth flow is being interrupted before the result could be delivered back to the caller of `WebAuthenticator.AuthenticateAsync`.
I have the feeling it has something to do with `NoHistory` (and the other flags) being used [here](https://github.com/xamarin/Essentials/blob/develop/Xamarin.Essentials/WebAuthenticator/WebAuthenticator.android.cs#L122). What would be the drawbacks of not adding these flags?

### Basic Information
- Version with issue: 1.5.3.1
- Platform Target Frameworks:  Android 10.2 

### Screenshots
![image](https://user-images.githubusercontent.com/2863198/80810605-83d75680-8bc4-11ea-9e14-8b952619f7ca.png)

### Reproduction Link
[WebAuthProblem.zip](https://github.com/xamarin/Essentials/files/4564534/WebAuthProblem.zip)

**Comment by tipa** [comment]
I think there is even more room for improvement for the auth flow on Android. I would recommend using a similar pattern as [this library](https://github.com/openid/AppAuth-Android), especially [this part is very interesting](https://github.com/openid/AppAuth-Android/blob/f1dbeb51f4d905523d804d70363abdb00728d99c/library/java/net/openid/appauth/AuthorizationManagementActivity.java#L39).
Having a "Authorization Management Activity" between the calling activity and the browser would also make a call to `Platform.OnResume()` redundant and the library is even easier to use.

**Comment by tipa** [comment]
Another problem I identified is that [this](https://github.com/xamarin/Essentials/blob/develop/Xamarin.Essentials/WebAuthenticator/WebAuthenticator.android.cs#L102) returns a [singleton](https://github.com/xamarin/AndroidX/blob/master/source/androidx.browser/browser/additions/CustomTabsActivityManager.cs#L13).
If authentication is performed multiple times and the initial parentActivity got destroyed [this line](https://github.com/xamarin/AndroidX/blob/master/source/androidx.browser/browser/additions/CustomTabsActivityManager.cs#L94)  returns false and [the system browser fallback is used](https://github.com/xamarin/Essentials/blob/develop/Xamarin.Essentials/WebAuthenticator/WebAuthenticator.android.cs#L108). Therefore I would rather use the `CustomTabsActivityManager` constructor directly.

I copied a lot of the code directly into my project and adjusted it, it is possible that these changes introduced these problems. If that is the case, I apologize :)

**Comment by chrisstaley** [comment]
I've also been running into the initially reported issue. The very first time I try to complete the auth flow on an Android device without cached Google credentials, when the auth response comes back from Google, the browser appears to redirect back to itself and the auth flow gets hung (see below) and never returns to the mobile app.

![image](https://user-images.githubusercontent.com/7912924/81979310-bd638500-95fa-11ea-8280-bb4a7f49a386.png)


Interestingly, it appears to be (partially?) due to a race condition. The issue does not present itself in the emulator if I introduce a delay in my `WebAuthenticatorCallbackActivity` like so:
```C#
protected override void OnCreate(Bundle savedInstanceState)
{
    // HACK: only works on emulator
    Thread.Sleep(2000);

    base.OnCreate(savedInstanceState);
}
```
However, this workaround does not appear to have an effect on an actual device.

There also appears to be a common denominator between @tipa's case and my own in that we both have 2FA turned on for our Google accounts.

**Comment by mattleibow** [comment]
This was fixed in https://github.com/xamarin/Essentials/pull/1511
