### ISSUE TITLE
[Bug] Share.RequestAsync does not open a share sheet on iPad iOS 13.4.1[Bug] 

### ISSUE THREAD

**Issue by maschunya** [xamarin/Essentials#1282]
### Description
The sharing works fine on iPhone and even on iPad iOS13.3, but not on iPad's with iOS13.4.1 No share sheet appears.
### Steps to Reproduce

Just call a Share.RequestAsync, optionally on the main thread.
                    await Share.RequestAsync(new ShareFileRequest
                    {
                        Title = Title,
                        File = new ShareFile(filepath, contentType)
                    });

### Expected Behavior
a share sheet should appear
### Actual Behavior
nothing appears
### Basic Information

Version with issue: Xamarin.Essentials 1.5.3.2
Last known good version: none
IDE: Microsoft Visual Studio Community 2019
Version 16.5.5
Xamarin.iOS 13.16.0.13
Nuget Packages: Xamarin.Essentials 1.5.3.2
Affected Devices: iPad

**Comment by jamesmontemagno** [comment]
This was fixed in https://github.com/xamarin/Essentials/issues/1247 I will have to reset, but best practice is to set a source rect.

Do you see any output?

**Comment by davehump** [comment]
This has been fixed

**Comment by its-stark** [comment]
There still is an issue if you are using a PCL project.
The solution for me to get the share view to the right position on the iPad screen would be to use **PresentationSourceBounds**. Unfortunately this is not possible when using PCL because the option is only available for netstandard != 1.0 as seen in this screenshot from the sources:
![2DCB2856-9B92-4733-BD53-3D47AB0691C9](https://user-images.githubusercontent.com/2984627/93271898-a30e0380-f7b4-11ea-9bb6-55e450c0c51f.png)
I guess when using PCL NETSTANDARD1_0 is default, but I didn't dig into that much.
