### ISSUE TITLE
[Bug] WebAuthenticator - Switching apps while in browser loses the browser window.

### ISSUE THREAD

**Issue by SpajicM** [xamarin/Essentials#1336]
### Description
Switching apps while in authentication flow closes browser and it's not visible in recent apps.

### Steps to Reproduce

1. Start web authenticatior
2. Minimize/switch to another app
3. Go back to your app

### Expected Behavior
Browser window is open where I've left off.

### Actual Behavior
Browser is closed.

### Code
`[Activity(NoHistory = false, LaunchMode = LaunchMode.SingleTop)]`

`    [IntentFilter(new[] { Intent.ActionView } , Categories = new[] { Intent.CategoryDefault, Intent.CategoryBrowsable }, DataScheme = "hr.travelsoft.callback" )]`
`    public class WebAuthenticationCallbackActivity : Xamarin.Essentials.WebAuthenticatorCallbackActivity`
`    {`
`    }`

**Comment by robertmadril** [comment]
We have encountered this issue, as well, specifically on Android. 

This especially impacts our user flow as we utilize TOTP codes that are delivered via SMS. Users are required to switch to their native messaging app in order to retrieve this code and input into the authentication flow. Unfortunately, this bug causes users to start over again.

_Resolutions Attempted_ 

•Removing NoHistory as an Activity annotation in the WebAuthenticationCallback class
•Adding onCreate() into the callback activity
•Attempting to add various other Intent flags

**Comment by sbxamdev** [comment]
Hello, I encountered the same issue in my Xamarin.Forms app, but its only an issue on Android. On iOS, the browser is not closing.  Any solution for this?
