### ISSUE TITLE
Add Camera and Recording API

### ISSUE THREAD

**Issue by kyle-john** [xamarin/Essentials#141]
[Android Document](https://developer.android.com/guide/topics/media/camera.html)
[iOS Document](https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture)
[UWP Document](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/)

**Comment by kyle-john** [comment]
It may help with features such as QR code recognition.

**Comment by alfredmyers** [comment]
+1 for the "QR code recognition" part.

Meanwhile, I'm gonna take a look at @Redth 's [ZXing.Net.Mobile](https://github.com/Redth/ZXing.Net.Mobile)

**Comment by Redth** [comment]
There's a lot of variables and considerations that go into QR code recognition....

First of all you have to decide if you use the system built in stuff which not every platform supports (I don't believe UWP supports this, and Android would mean a hard dependency on Google Play Services - Vision).  Otherwise you need to use something like ZXing.Net to do the decoding which is non-trivial.

Not to mention there's a lot of moving UI parts involved in being able to do QR code recognition.

I like the spirit of this idea, but I think this is too heavy to pull into a project like Caboodle.

**Comment by mattleibow** [comment]
I think we should remember the idea behind Caboodle - it is to provide a uniform, clean API for _existing_ platform features/functionality. QR code reading is not really a platform feature, but rather a nice feature.

**Comment by Redth** [comment]
We are definitely going to add some of this, we purposefully left it out for now since it's a complicated thing to implement properly (especially on Android).

**Comment by jamesmontemagno** [comment]
Need to split this into two proposals. There is really:

* AudioRecorder
* Camera
* ImagePicker

I am going to close this and open new proposals
