### ISSUE TITLE
MediaPicker Take Photo iOS incorrect FullPath[Bug] 

### ISSUE THREAD

**Issue by oleksandrtretiak** [xamarin/Essentials#1631]
FullPath looks like the same as FileName.
### Screenshots

<img width="494" alt="Screenshot 2021-01-13 at 14 19 50" src="https://user-images.githubusercontent.com/6115977/104460176-6a413800-55b6-11eb-9a5f-e81899d7e464.png">

**Comment by IngweLand** [comment]
I do not think this is a bug. As far as I understand, the physical file is not created when the photo is captured. Not sure why they extend the result from `FileResult` in that case, probably for convenience. As such, they had to include that FullPath.

        internal UIImageFileResult(UIImage image)
            : base()
        {
            uiImage = image;


            FullPath = Guid.NewGuid().ToString() + FileSystem.Extensions.Png;
            FileName = FullPath;
        }

**Comment by olitee** [comment]
I find this inconsistency between iOS and Android odd: 

iOS does not create a file - but Android does. So the handling and clean-up logic I write ends up being platform specific. Unless I've missed something?

**Comment by IngweLand** [comment]
My pull request fixes that issue

**Comment by mattleibow** [comment]
The file path returned but the pickers are all dependent on where the file comes from. Some files are from a library, so making a local copy is not always done. For example, picking files from the iOS photos library will return the original. Android does something similar if you have the permissions to the SD card and the photo was on there.

Instead of making a copy, you can just open the file and read it. If you want a copy, then just copy the stream using `OpenReadAsync`. The path is just where the file was picked from. If the OS does not want to give this out, then we generate a guid so at least the file names are unique.

**Comment by kunalenterprise** [comment]
@mattleibow What happens in case when using PickPhotoAsync(). I am getting guid in filename and path.
