### ISSUE TITLE
[Enhancement] QR/Barcode scanner!

### ISSUE THREAD

**Issue by maksym-husiev** [xamarin/Essentials#1677]
## Summary
It will be great to have some kind of QR code scanner just as part of Essential to avoid third-party library usage.

**Comment by mattleibow** [comment]
This is quite a big set of things to add. I would strongly recommend using the very good zxing:

https://www.nuget.org/packages/ZXing.Net.Mobile.Forms

I am going to close this as I don't think we will add it because Essentials is really about exposing native features in a shared way. This issue is about new features not found on devices.

**Comment by maksym-husiev** [comment]
The latest stable version of proposed packages was released 04.04.2018 and iOS already has native barcode recognising functionality (don't know if it can be used), not sure if such things exists on Android

**Comment by jamesmontemagno** [comment]
@Redth  is updating Zxing right now, it is active and there are new preview releases avaialble.

I agree here that this is out of scope right now.
