### ISSUE TITLE
[Enhancement] Allow MediaPicker API to pick both photos and videos

### ISSUE THREAD

**Issue by velocitysystems** [xamarin/Essentials#1704]
## Summary
Allow the `MediaPicker` API to pick **both photos and videos** with a single API call i.e. similar to the media picker used in popular apps such as Instagram. Currently, the API only allows either photos or videos seperately.

## API Changes
**New Methods/Objects**

_Method_
`MediaPicker.PickAsync(params MediaType[] mediaTypes)`
- `MediaType` array permits multiple media types to be passed
- Note: `params` syntax allows a _single_ enum type to be passed

_Enum_
```
MediaType
- MediaType.Photo
- MediaType.Video
```

**Existing Methods**
To maintain backward-compatibility, `PickPhotoAsync` and `PickPhotoVideoAsync` should be retained as a passthrough to the new method `PickAsync`.

## Intended Use Case
```
async Task PickAsync()
{
    try
    {
        var media = await MediaPicker.PickAsync(MediaType.Photo, MediaType.Video);
    }
    catch (Exception ex)
    {
        Console.WriteLine($"PickAsync THREW: {ex.Message}");
    }
}
```

If this enhancement is approved, I'd be happy to contribute the work as a PR.

**Comment by 1Cor125** [comment]
I want to +1 this feature request and the suggestion to make this an additive change. It seems we've pigeon-holed the `MediaPicker` API to pick _either_ photos _or_ videos whereas many apps today allow you to just open the Photo Library and choose photos _and_ videos. In our case, we are resisting urge to just add two menu options to our UI, because our UX spec calls for an option called "Add From Photos" which should allow the user to add photos and videos. Unfortunately we will have to write our own picker to do that, which sort of negates the advantage of using Essentials for this. Could we get a response from the team to see if it's worth waiting for this enhancement or whether we should proceed with a custom picker?

**Comment by 1Cor125** [comment]
Any update on this? I notice that @davidbritch mentioned this issue [here](https://github.com/MicrosoftDocs/xamarin-docs/issues/3254#issuecomment-788886241). Does that mean that this enhancement request has been lumped in with the request for an audio API, as far as priority @davidbritch and @Redth? To have the option to pick an item from a collection of your videos _and_ photos at the same time is a lot more common than picking an audio file. For example, in WhatsApp on iOS you can tap the plus sign next to the text entry in a chat and you get an option called `Photo & Video Library`. That's what we are trying to implement here. 

I just want to make sure I understand the thinking of the team on this because we are going to need this functionality it an upcoming release.

**Comment by velocitysystems** [comment]
@mattleibow @jamesmontemagno I'd really be interested in your comments on this proposal.

Like @1Cor125, we have a pressing need to pick both photos and video a single operation (i.e. Like WhatsApp) and this proposed change only adds functionality and does not remove any. As mentioned, I am happy to contribute a full PR implementation on this.

**Comment by dimonovdd** [comment]
This is probably incorrect on my part. 
But as a temporary solution until MAUI is released, you could use [this plugin](https://github.com/dimonovdd/Xamarin.MediaGallery). I hope that in the future I will be able to add this to MAUI

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Essentials is now in maintenance mode, this will not happen anymore for Xamarin.Essentals. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
