### ISSUE TITLE
WebAuthenticator iOS - Sign out does not delete the cookies and we are unable to sign in as a different user

### ISSUE THREAD

**Issue by JRallee** [xamarin/Essentials#1712]
### Description
Using WebAuthenticator for app sign in/out. Even after successful sign out, cookies aren't cleared and next time sign in logs in without prompting for user details.

### Expected Behavior
After sign out, when the user tries to sign in again, it should open the page which accepts user id (ex. Azure Active directory login page)

### Actual Behavior
App just signs in with the previous user. Unable to really switch users.

### Basic Information
Only workaround to achieve it is, 
Settings --> Safari --> Clear History and development data

###Note - Android seems to be working fine.

Tried below option, but no cookies are found
authContext.TokenCache.Clear();
var cookieStorage = Foundation.NSHttpCookieStorage.SharedStorage;
foreach (var cookie in cookieStorage.Cookies)
{
   cookieStorage.DeleteCookie(cookie);
}

Have gone through other similar issues in this repo like,
https://github.com/xamarin/Essentials/issues/1223
https://github.com/MicrosoftDocs/xamarin-docs/issues/2814

but unable to find a concrete solution.

Any suggestions/solutions would be of great help

Thanks

**Comment by vincentcastagna** [comment]
Just in case, clears the receiver’s cache, removing all stored cached URL responses, you can try to `NSUrlCache.SharedCache.RemoveAllCachedResponses();` 

Try cleaning both storage cookie location like so, I noticed some cookies are still present there even if I'm on 14 ... 
```
				WKWebsiteDataStore.DefaultDataStore.HttpCookieStore.GetAllCookies((cookies) =>
				{
					foreach (var cookie in cookies)
					{
						WKWebsiteDataStore.DefaultDataStore.HttpCookieStore.DeleteCookie(cookie, null);
					}
				});
			
```

**Comment by dcmarlon** [comment]
Hey what did you on android to work on clearing the cookies?

**Comment by curtisconner** [comment]
How can i suggest that we add an option to the WebAuthenticator.AuthenticateAsync

we need to be able to pass in an option for various platforms.  I am currently using a modified version of essentials so that i can set the was.PrefersEphemeralWebBrowserSession = true;  This tells the browser not to use the local cookies.  I set this to false on the initial login, but if i need to refresh the token and i need to prompt for the login i set this to true.

I see that there are others what want to set the timeout value, this again could be done via an option.  Very simple change for the iOS system and made the login workable for iOS

**Comment by marcelbeeker** [comment]
Is there any news about how to clear the session cookie in Android. I'm waiting for a long time to fix this issue.

**Comment by samirgcofficial** [comment]
?

**Comment by OmarAlejandroNavarroCerda** [comment]
con estas dos simples lineas pueden borrar las cookies 

            CookieManager.Instance.RemoveAllCookies(null);
            CookieManager.Instance.Flush();
