### ISSUE TITLE
Xamarin.Essentials.Contacts.PickContactAsync

### ISSUE THREAD

**Issue by amolk7** [xamarin/Essentials#1794]
### Description
      try
            {
                var contact = await Xamarin.Essentials.Contacts.PickContactAsync();
                if (contact != null)
                {
                   // Some Code
                }
            }
            catch (System.Exception ex)
            {
                 
            }   
            
      On calling this function Contact Picker get open, but when user cancel / press back arrow then it throws error "System.Threading.Tasks.TaskCanceledException: A task was canceled."    

Tested on Android 10 (Oppo F17)

### Expected Behavior
Picker must close without Exception
### Actual Behavior
Exception thrown and not able to catch using try catch.
### Basic Information

- Version with issue: 1.6.1
- Last known good version: N/A
- IDE: Visual Studio
- Platform Target Frameworks: 

  - Android: 10

- Android Support Library Version: 
- Nuget Packages: 1.6.1
- Affected Devices: OPPO F17

**Comment by PATRICKdallat** [comment]
Same issue for getallcontacts

**Comment by AmrAlSayed0** [comment]
I think the problem is here https://github.com/xamarin/Essentials/blob/7218ab88f7fbe00ec3379bd54e6c0ce35ffc0c22/Xamarin.Essentials/Platform/Platform.android.cs#L390

Pressing back cancels the Activity which cancels the task instead of setting the result of the task to null. Not sure if this was the intention or not, but there is 2 way to fix this. Either change the IntermediateActivity to set the result the of the Task to null (which will affect all the features using IntermediateActivity and be a braking change) or create another exception type (e.g. UserCancelledException) that users of the method can handle.

**Comment by dimonovdd** [comment]
This is a valid exception. We need to understand why it doesn't fall into Catch

**Comment by dimonovdd** [comment]
I've tested this on multiple devices. I can catch this exception. 
You can view the code in [the sample project](https://github.com/xamarin/Essentials/blob/7218ab88f7fbe00ec3379bd54e6c0ce35ffc0c22/Samples/Samples/ViewModel/ContactsViewModel.cs#L37)

**Comment by amolk7** [comment]
After Clean install its working as expected. 
Thank you @dimonovdd
