### ISSUE TITLE
[Enhancement] Launcher - Add option to not use LaunchAdjacent flag on Android

### ISSUE THREAD

**Issue by grahampett** [xamarin/Essentials#1817]
## Summary
The Launcher PlatformOpenAsync methods on Android set the LaunchAdjacent flag on the intent on Android, causing the link to open in split-screen mode if this is enabled on the phone. This is not always desirable, so it would be good to have an option to disable this.

## API Changes

Browser does this with BrowserLaunchFlags.LaunchAdjacent, so I would suggest adding a similar API to Launcher.

## Intended Use Case
Launching a URI from an app where you want the launched app/browser to always appear full-screen rather than split-screen.

**Comment by joemather** [comment]
Totally agree.

I want a full-screen map, but it's not possible because `ActivityFlags.LaunchAdjacent` is hardcoded.

https://github.com/xamarin/Essentials/blob/bc74dce78a96942a7941f2f85f1e13a0cdb53595/Xamarin.Essentials/Map/Map.android.cs#L67

There should be an option to disable `ActivityFlags.LaunchAdjacent`.

**Comment by jfversluis** [comment]
I think this has been fixed in the most recent version already!
