### ISSUE TITLE
Awaited Calls to Share.RequestAsync do not block as expected

### ISSUE THREAD

**Issue by Adam-Langley** [xamarin/Essentials#1899]
### Description
Share API is async, however it immediately returns despite not having completed the Share operation.
This is a problem, because it means there is no way to disable a button while the platform Share window is open, then re-enable it when the share operation has completed.
On iOS, if you request a UIActivityViewController be presented twice, the application may freeze.

### Steps to Reproduce

1. Call await Share.RequestAsync(...)

### Expected Behavior
Call should block until user either completes the sharing operation (i.e, picks a mode, print, dropbox, etc), or cancels the operation.

### Actual Behavior
The execution immediately proceeds.

### Basic Information

  - iOS:  iOS15

**Comment by cdavidyoung** [comment]
My application needs to do a Share.RequestAsync for both an XML and ZIP file in response to a button.  On iOS it results in two share dialogs so that the user can specify one and then the other.  However, on Android it seems that the second Share.RequestAsync cancels the first.  This is problematic.

**Comment by TRadigk** [comment]
I would like to point out that on android this issue is not fixed. 
In my app I am exporting a file with RequestAsync and it always failed since I delete the file after I awaited the request.
