### ISSUE TITLE
[Bug] The type or namespace name 'Platform' does not exist in the namespace 'Xamarin.Essentials'

### ISSUE THREAD

**Issue by acaliaro** [xamarin/Essentials#1964]
### Description
I have opened a Xamarin Android project today (it has worked fine till some days ago) and I have this error

**The type or namespace name 'Platform' does not exist in the namespace 'Xamarin.Essentials'**

Same problem here: #683 

### Steps to Reproduce

I don't know how to reproduce it. If I create a new Xamarin Android project, Xamarin essentials is already in the project and it works. 

### Expected Behavior
The project should compile

### Actual Behavior
The project does not compile

### Basic Information

- Version with issue: 1.7.1
- Last known good version: 1.7.1
- IDE: VS2022
- Platform Target Frameworks: 
  - iOS:  
  - Android:  9.0
  - UWP:   
- Android Support Library Version:  28.0.0.3
- Nuget Packages:
- Affected Devices:

**Comment by acaliaro** [comment]
I have found a solution. 
I have updated manually the csproj (it was old) starting from a new csproj.
I have set the targetsdk to 12
now it works

**Comment by DanielRBowen** [comment]
I got this bug when using a fresh Xamarin.Forms project template which the AndroidManifest.xml android:targetSdkVersion is set to 31.

Here is the AndroidManifest.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.eow.kiosk.xamarin">
    <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="31" />
    <application android:label="Eow.Kiosk.Xamarin.Android" android:theme="@style/MainTheme"></application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>
```

**Comment by JayD2019** [comment]
Hi,  I have the same issue in a Xamarin.Android project that targets Android 9.0 
It worked fine for over a year until YESTERDAY Nov 1 2022.  WHY now?  The update number of the package has not changed.  I have temporarily commented out the affected lines in MaInActivity.cs so that it compiles,  but I need a fix.  The app will not run without this call; Preferences in the app do not work for starters.

I read in https://github.com/xamarin/Essentials/issues/683 that target platform needs to be 8.1 (or higher I presumed). This now seems to have changed, as there seems to be no issue with the Platform section in Xamarin.Essentials if the Target version is set to 12.

However,  I have to keep my target as 9 for development as the Android Designer does not work when targeting 11/12.  
( https://github.com/xamarin/xamarin-android/wiki/JDK-11-Warning )   
If I now have to change target platforms AND Jdk versions in order to debug my software and then switch back for design work, this is going to add an overhead, as I will need to change a whole host of Nu-Get packages each time also.    Am I missing something? 
Please help.

 Thanks
J

**Comment by brminnick** [comment]
For the latest release, Xamarin.Essentials v1.8.0, this error pops up again. 

The solution this time is to increase the `TargetFrameworkVersion` to `v13.0`

I do into more detail here in this StackOverflow answer: https://stackoverflow.com/a/76899725/5953643

**Comment by AmaluThomas** [comment]
Azure pipeline fails for android project after upgrading xamarin.essentails to 1.8.1.

<PackageReference Include="Xamarin.Essentials"><Version>1.8.1</Version></PackageReference>

Locally the project is building and image selection also work perfect.
Android app's TargetFrameworkVersion to v13.0 
android:targetSdkVersion="33"

This upgrade is required as select image and take photo is not working for android 13+.

Error: The type or namespace name 'Platform' does not exist in the namespace 'Xamarin.Essentials' (are you missing an assembly reference?)

Can some one suggest a solution.?

**Comment by AmaluThomas** [comment]
@brminnick

**Comment by brminnick** [comment]
Please read the [Release Notes](https://github.com/xamarin/Essentials/releases/tag/1.8.1) before tagging me

The [Release Notes for v1.8.1 ](https://github.com/xamarin/Essentials/releases/tag/1.8.1) show that the minimum Android API is v34 targeting Android 14. 

![image](https://github.com/xamarin/Essentials/assets/13558917/12d16186-8f8f-4065-95ac-150869748838)

**Comment by darm10** [comment]
> The solution this time is to increase your Android app's `TargetFrameworkVersion` to `v13.0`

It literally states **Add compatibility** not the minimum!
