### ISSUE TITLE
[NAB] Access to the path is denied when picking txt files on UWP using FilePicker

### ISSUE THREAD

**Issue by mattenbo** [xamarin/Essentials#1995]
### Description
Access to the path is denied when picking *.txt files using Xamarin Essentials FilePicker on UWP

### Steps to Reproduce

1. Using Attached code and UWP
2. Click on button to select a text file
3. access is denied

### Expected Behavior
According to https://docs.microsoft.com/en-us/xamarin/essentials/file-picker?tabs=uwp , no additional setup is required. Using filepicker should ensure that access is granted.

### Actual Behavior
Access is denied for *.txt files except from the Environment.SpecialFolder.LocalApplicationData
[FilePick.zip](https://github.com/xamarin/Essentials/files/8512301/FilePick.zip)

### Basic Information

- Version with issue:  All?
- Last known good version:
- IDE: Visual Studio 2022
- Platform Target Frameworks: 
  - UWP:   Windows 10, Version 2004 (10.0, Build 19041)
- Nuget Packages: Xamarin Essentials
- Affected Devices: Windows laptop

### Reproduction Link

 Attached

**Comment by symbiogenesis** [comment]
Probably an issue with UWP itself, not Xamarin.Essentials

**Comment by symbiogenesis** [comment]
Found the issue. UWP uses Windows.Storage instead of System.IO to read files. So you don't actually have an access problem, you have an API problem.

The nuget package [PCLExt.FileStorage](https://github.com/PCLExt/PCLExt.FileStorage) solves this in a cross-platform way

**Comment by mattenbo** [comment]
I have installed PCLExt.FileStorage version 1.3.2 as in the attached project (also tried 1.4.0, 1.4.1 and 1.3.0)
Still not working - I am still getting Access is denied for *.txt files except when picked from the Environment.SpecialFolder.LocalApplicationData
I cannot see any reference in the project to Windows.Storage.  Could you perhaps amend this project if you have managed to get it working? Thanks  for your time.
[FilePick.zip](https://github.com/xamarin/Essentials/files/8935211/FilePick.zip)

**Comment by symbiogenesis** [comment]
Fixed your project. You needed to use the new API from that nuget project, not just reference it. Also needed uninstall that nuget project from everything but the common netstandard project, to get around a runtime error. Finally, I made the label text white, so that you can see it on top of the black background.

If you have more problems later you could add the following line inside the <Capabilities> tag in your appxmanifest, inside the UWP project. (right-click it and select View Code)

`<uap:Capability Name="documentsLibrary"/>`

But the attached zip file works for me without any extra permissions.

[FilePick.zip](https://github.com/xamarin/Essentials/files/8935990/FilePick.zip)

**Comment by symbiogenesis** [comment]
Updated the zip to include a file I missed
