### ISSUE TITLE
SecureStorage Alias control

### ISSUE THREAD

**Issue by craylward** [xamarin/Essentials#234]
It would be cool if we have optional control over the Alias parameter used to store values in the Keystore/Keychain. Maybe adding a default parameter to the SetAsync/GetAsync method or exposing the Alias property.

**Comment by jamesmontemagno** [comment]
Is there a specific use case for this? Would help us better understand why and how it could be used.

we use: {AppInfo.PackageName}.xamarinessentials for it currently.

**Comment by nastutusha** [comment]
Hi, we're having an issue migrating from sameerkapps SecureStorage to Xamarin Essentials Secure Storage. As all our users' keys are stored within different alias we can't retrieve them and they're lost. It would be great to have access to Alias parameter or maybe you can think of another solution, because we definitely don't want all our users to logout after new app release.
