### ISSUE TITLE
Low Pass Filter for Android Compass

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#337]
Android compass is very spotty and a low pass filter should be applied optionally to smooth out the return values. This should be optional.

To Add to Compass:

```csharp
public static bool ApplyLowPassFilter {get;set;}
```

**Comment by Mrnikbobjeff** [comment]
@jamesmontemagno We needed a compass for a University group project and had problems with the Android compass. We decided to fork Essentials rather than roll our own compass. Even though this is tracked back to proposal status I would really like to see this in the master, as the android compass is very spikey without filtering. We created a pull request and added a sample property to see the benefit.
