### ISSUE TITLE
Explore Converting .NET Standard Assembly to a Reference Assembly

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#346]
https://oren.codes/2018/07/03/create-and-pack-reference-assemblies/

Need to understand more why and how and implications as there is some shared logic in some of the shared code.

**Comment by onovotny** [comment]
I just made this easier:
https://oren.codes/2018/07/09/create-and-pack-reference-assemblies-made-easy/

The Extras now includes almost everything you need.

**Comment by jamesmontemagno** [comment]
Still confused how to do this and the advantage here. We do have some logic inside of the .net standard library. Not sure if there is a lot of benefit to do this.

**Comment by jamesmontemagno** [comment]
Closing for now as I don't think it is needed.

**Comment by mattleibow** [comment]
@onovotny Can this be done for a specific target framework? We are using multitargeting, so what should we do to get the netstandard to be marked as ref?

**Comment by onovotny** [comment]
Yes, this can work for multi-targeting. This would prevent the netstandard one from being used at runtime since there would not be a runtime asset.

To make this work, you'd follow the docs and create another project that includes all the original files via a glob. The TargetFrameworks there can be different than the source project.

The end result would be to have the real libs in \lib and the netstandard in \ref.

**Comment by jamesmontemagno** [comment]
In general though it would be used due to how it runs anyways... technically there is some logic like unit converters that could be used in the .net standard version.
