### ISSUE TITLE
Add Jailbreak Detection API

### ISSUE THREAD

**Issue by aritchie** [xamarin/Essentials#359]
## Description of Feature

Detect the standard forms of jailbreaking techniques that can be performed on Android & iOS - UWP is by nature jailbroken (though sadly will return false).  The jailbreaks routines that will be implemented are considered "safe" by most payment gateway services for mobile devices which does make this API relevant to POS LOB applications.

## API Declaration

Integration Point: DeviceInfo

```csharp
bool IsJailBreakDetected { get; }
```

### Documentation links for supported platforms

* Does not exist - existing implementation found here: https://github.com/aritchie/deviceinfo/tree/master/Plugin.DeviceInfo/Platforms

**Comment by Redth** [comment]
I'm really leery of this one still.

One idea I've had is to maybe change the naming to insinuate an implicit lack of confidence or at least insurance in this value being accurate and correct.  We don't want the liability of returning `false` when really the answer is `true` but we simply did not detect it.

What if we name this to `IsJailBreakSuspected` ?

**Comment by aritchie** [comment]
Just document your way out of it.  Stick a  ///<summary>Uses common/known jailbreak techniques (not guaranteed to catch all)</summary>

**Comment by Redth** [comment]
Yeah we definitely would need to document this like crazy if we decide to incorporate it.  Let me bring this up to some others internally to see what they think.

**Comment by frankhaugen** [comment]
This is maybe a general "device security" thing.  Securing apps is starting to become a great concern and so maybe a larger effert in the community, should be geard towards making it easier to make secure apps. Yes dotfuscator etc. does an acceptable job, but there are getting to be a lot of tools to reverse obfuscation.

But this is a major de-railing of this discussion

**Comment by Redth** [comment]
I think this boils down to us not wanting to create a false sense of security to developers. This is such a cat and mouse space with products built specifically around this sort of thing. Sure we could document the inevitable shortcomings of such a basic implementation but arguably that's not really useful still to someone depending on this feature. I sure wouldnt want to build an app that only might catch this, because presumably if I care to catch some cases, I probably need to catch all cases. 

Anyways, appreciate the input here but it's just not on our roadmap for now. I think this is a great space for a community plugin to exist (which it seems it does).
