### ISSUE TITLE
AbsoluteUri vs OriginalUri vs IdnMapping

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#368]
Currently in our code we are using OriginalUri, however this causes issues for Unicode URL. AbsoluteUri could be better too, but perhaps not in all instances....

https://stackoverflow.com/questions/35875376/uri-absoluteuri-vs-uri-originalstring

One recommendation is to use Idn mapping for Urls...
https://stackoverflow.com/questions/36685160/unicode-url-could-not-initialize-an-instance-of-the-type-foundation-nsurl-t

This directly impacts the Browser API, #356, and #355 and should be assessed before pulling in.

**Comment by Mrnikbobjeff** [comment]
For the Browser API we definitely should use AbsoluteUri, because OriginalUri does not escape strings. This is especially desired by the browser. Relative URI support is not very important for the browser API which is one of the weaknesses of AbsoluteUri. The benefit of using OriginalUri is that it shifts all responsibility for URI validity to the consumer. OriginalUri does exactly what the name implies, returns the string used to construct the uri.

**Comment by Redth** [comment]
So my understanding is we should probably use IDN mapping for hosts, and percent encoding for the path and query.

**Comment by Redth** [comment]
I have a PR open for this #393 

Basically, the PR fixes up any puny code (IDN) domain names, and then uses the % encoded path and query from the uri (so what AbsoluteUri is doing) to construct a _safe_ encoded version of the URL to pass to each platform.

The platforms seem to all handle this correctly.
