### ISSUE TITLE
SMS API - Add ability to add attachment

### ISSUE THREAD

**Issue by nbsoftware** [xamarin/Essentials#382]
### Steps to Reproduce

Build an app that uses the SMS API to prefill an SMS with recipient & text

### Expected Behavior

When I click on the photo icon within the native sms interface I expect to be able to select a photo to add to the sms being written

### Actual Behavior

Nothing happens when I click on the photo icon from the sms interface

### Basic Information

Device Tested On: iPhone 6s / 7 plus - iOS 11.4
Not tested on physical Android yet.
Simulator Tested On: N/A
Version of VS: Version 7.5.3 (build 7) for Mac
Version of Xamarin: Xamarin.iOS 11.12.0.4

> VS bug [#735663](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735663)

**Comment by jamesmontemagno** [comment]
So from all my reading the Message composer must attach the photo and they disable the ability to do this. Not sure why. I have made this a proposal to add attachments to an sms.

**Comment by Redth** [comment]
Looks like iOS allows for `MFMessageComposeViewController.AddAttachmentData(NSData data, string utiIdentifier, string filename)`.

On Android I think we can set an EXTRA_STREAM `smsIntent.PutExtra(Intent.ExtraStream, Uri.Parse(uri));` additionally we may need to set any sms with attachments to use `mms` instead of `sms`.

UWP seems to support this easily.

We may want to consider the state of [Android File Providers](https://github.com/xamarin/Essentials/issues/130)  before we implement this.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
