### ISSUE TITLE
Add Course/Bearing and Speed to the Location Class

### ISSUE THREAD

**Issue by mjorrens** [xamarin/Essentials#400]
Can you guys add Course/Bearing and Speed as properties to the Location Class?

Android returns Bearing (direction the device is moving) and speed.

iOS returns Course (direction the device is moving) and speed.

Course is the same as Bearing.

Note that compass returns where the device is facing, not the direction in which the device is moving. Looks like you have that one covered.

Thanks!

EDIT: API Proposal

# API Proposal

## Add:

```
public class Location
{
        public double? Speed { get; set; }
        public double? Bearing { get; set; }
}
```

Both `Speed` and `Bearing` should be null if they are unavailable for a given set of location data on a platform.

**Comment by Redth** [comment]
Some research about speed:

## UWP

`Nullable<double> Speed` The speed in meters per second.

Null value indicates no heading available.

## Android
`double Speed`  Get the speed if it is available, in meters/second over ground.

0.0 value indicates no speed is available (presumably 0.0 is not likely to be possible, more like 0.00001 for a valid available speed that is close to 0)

## iOS

`double Speed` - The instantaneous speed of the device, measured in meters per second.

< 0 value indicates no speed is available

**Comment by DanielCauser** [comment]
Issue number 400!

**Comment by Mrnikbobjeff** [comment]
I implemented everything in this branch [here](https://github.com/Mrnikbobjeff/Essentials/tree/LocationImprovements). I tested it on android, it worked there. I do not own a uwp device though, so I will not be able to check whether my changes work there. iOS will also take time to test as I don't always have a iOS device available. The changes were pretty straightforward though because of all the work @Redth put in. I will create a pr as soon as I am able to test it on iOS.

**Comment by Redth** [comment]
👍 Please make a PR and we will merge it into a local branch and fill out the UWP bits :)

**Comment by jamesmontemagno** [comment]
I would say that we can document that these are pretty inaccurate and I get tons of complains on my Geolocator plugin, but I think docs will help.

**Comment by Mrnikbobjeff** [comment]
@Redth done:)

**Comment by mjorrens** [comment]
I have actually had good success with James' Geolocator plugin on Android (tested on a Galaxy Note 2) and iOS (tested on an iPhone 6S) with accuracy (walking and driving). There are a bunch of settings to get right though on each platform to increase accuracy and frequency of updates.

**Comment by jamesmontemagno** [comment]
Should it be called Bearing? Course? Heading? Probably Heading....

**Comment by Redth** [comment]
For some reason I thought UWP called it bearing as well..  They all call it something different.  Now that I see that, I do think Heading is probably best.

**Comment by mattleibow** [comment]
Merged

**Comment by LadderLogic** [comment]
Speed sample smoothening:
Everybody that uses the Speed from the Location would need to do some kind of smoothening/fitting to get an ~accurate value and Speed is mostly only relevant when collecting multiple samples anyway. Would it be worth including the fitting into the Xamarin Essentials library and perhaps also an Observable for the Speed?

**Comment by mjorrens** [comment]
I am finding the fastest I can get the updated GPS info with speed from Android and iOS is about once every 2 seconds. In testing my demo app in a driving scenario with two iOS devices, an Android device and the speedometer on the car, all are giving very accurate results.

I am sure for walking/biking applications where you want speed, you will want to do some smoothing. I would leave that up to the developer for their specific app and not include it as part of the library.

I guess it all comes down to the frequency of the GPS updates and the calculated distance between between those updates. If the distance is < x meters then smooth the reported speed else give the reported speed.

Lastly, I have read some posts that report that the speed given by iOS and Android is 10X more accurate than calculating the speed directly off the GPS coordinates given the time interval between GPS updates. That leads me to believe that the devices are already doing some sort of smoothing when reporting Speed.

**Comment by jamesmontemagno** [comment]
Any smoothing or filtering should be done by the parent application as we can not predict how developers will use the data or want to use it.

**Comment by LadderLogic** [comment]
Yes, I was indeed trying to get some accuracy under 10mph. Interesting that you mention that this speed is actually coming from the device itself. I was under the assumption that the essentials library was calculating this. 
That being said, there must be a special device mode to request speed/location continuously. I say this because, when I try to poll every 2 seconds or poll when the accelerometer changes, I see the location icon in the notification come on and off repeatedly. I don't see this with some other speed/location tracking apps, like Strava for instance or even google navigation. The location indicator stays on suggesting that there might be a mode that would publish more accurate/frequent location updates. Perhaps, it's just wishful thinking.
