### ISSUE TITLE
Proposal - Add Cross platform media playback support

### ISSUE THREAD

**Issue by pakbaz** [xamarin/Essentials#437]
### Description of the Feature
Ability to playback multimedia files (audio/video) cross platform. also include features such as background music streaming/playback.
There is a cross platform library exist here in [github ](https://github.com/martijn00/XamarinMediaManager)by [@martijn00](https://github.com/martijn00) here but there is no .Net Standard 2.0 support and there are many issues with it that has not been resolved and been stalled for months. It would be nice if Xamarin essential can pick it up and make a nice cross platform plugin for playing audio/video files as well as background streaming all in one simple interface

### API Declaration
CrossMedia.Play()
CrossMedia.Pause()
CrossMedia.Stop()
CrossMedia.Next()
CrossMedia.Previous()
CrossMedia.IsPlaying
CrossMedia.IsBuffering

Additional Classes or Structs needed
Media File is an option here with the stream, metadata, buffering info?
Also events such as playback stop, network interruption etc...

### Documentation links for supported platforms
[Android Document](https://developer.android.com/reference/android/media/MediaPlayer)
[iOS Document](https://developer.apple.com/documentation/mediaplayer)
[UWP Document](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayer)

**Comment by cfl777** [comment]
Though it would be great, Xamarin doesn’t always have the best support for these types of libraries either, with issues etc (xamarin google component lib is a good example). Not sure how much different it would be.

**Comment by jamesmontemagno** [comment]
I think that this one is extremely tricky and would need to know exactly how developers would want to use this API itself. For instance it is probably achievable to be able to abstract a way of playing an audio file, but does this mean we tap into platform specific notifications, handle headphone plug/unplug, artwork, etc. The differences between platform in that regards are extremely high especially when it comes to background streaming and attempting to abstract this would not be a great idea (I have done it in the past and it was a bad idea). So the scope of this would have to have very tight requirements.

**Comment by adamfisher** [comment]
I know how hard this one can be because I built a premium video player for Xamarin Forms and it took me three months to build it: 

https://github.com/adamfisher/Xamarin.Forms.VideoPlayer

Here is a small snippet of the cross-platform API surface area from the **Getting Started** guide:

## Player Properties

Common video player operations are described here.

| Property            | Description                                                                                                                                   |
|---------------------|-----------------------------------------------------------------------------------------------------------------------------------------------|
| AutoPlay            | Specifies that the video will start playing as soon as it is ready. Default value is False.                                                   |
| DisplayControls     | Specifies that video controls should be displayed (such as a play and pause button). Default value is True.                                   |
| FillMode            | Defines how the video content is displayed within the player layer's bounds. Default value is ResizeAspect.                                   |
| TimeElapsedInterval | The time interval in seconds for the TimeElapsed event firing to occur. Default value is 0 seconds which means TimeElapsed will not fire.     |
| Repeat              | Repeat video when playback is complete. Default is value False.                                                                               |
| Volume              | The volume level of the current media stream. The default is the value currently assigned to the system volume.	  							  |
| Source              | A local file path or remote URL to a video file.                                                                                              |
| CurrentTime         | A read-only bindable playback time for the current video.                                                                                     |
| State         	  | A read-only bindable property indicating the current state of the video player (e.g. Idle, Prepared, Playing, etc.)                           |
| IsLoading        	  | A read-only bindable property indicating the video is loading for playback.										                              |
<br/>

## Playback Events

This component gives you the ability to subscribe to a wide variety of events that typically occur during video playback with the event handlers below. The EventArgs that are passed to each event firing contain a wealth of information about the current state of the player (current time, total duration, volume level, etc.).

| Event              	| Description                                                                                                               	|
|--------------------	|---------------------------------------------------------------------------------------------------------------------------	|
| Playing            	| Notification the playback rate has changed to a non-zero rate due to the user pressing play or some other action.         	|
| Paused             	| Notification the playback rate has changed to zero due to the user pressing pause or some other action.                   	|
| TimeElapsed        	| Notification the specified number of seconds configured in the `VideoPlayer.TimeElapsedInterval` have passed.             	|
| Completed          	| Notification fires when the video player has reached the end of the playback stream.                                      	|
| Failed             	| Notification fires when the video player experiences an error during playback or during initialization of the media file. 	|
| PlayerStateChanged 	| Event notification fires when the video player's internal state machine changes state.                                    	|

<br/>

## Commands 

It's also possible to bind other Xamarin Forms controls such as buttons to common video player operations noted below. This could be useful in situations where you want to create your own cross-platform buttons for these operations and perhaps set `DisplayControls="False"` on the video player.

| Command      	| Description                          	|
|--------------	|------------------------------------	|
| PlayCommand  	| Begins playback of the media file. 	|
| PauseCommand 	| Stops playback of the media file.  	|
| SeekCommand  	| Seeks a specific number of seconds forward or backward in the playback stream. This command takes an integer command parameter equal to the number of seconds forward (positive number) or backward (negative number) to seek. |

**Comment by adamfisher** [comment]
Alternatively, Martijn has created a free one:

https://github.com/martijn00/XamarinMediaManager

**Comment by Redth** [comment]
This API is going to be too UI dependent to be considered in Xamarin.Essentials.  While there may be parts of it like background audio streaming that _could_ make more sense in the library, this feels like a bit heavy / out of scope for Essentials at this point in time. Glad to see there are some community plugins which make this work!
