### ISSUE TITLE
Secure Storage error even with Keychain entitlement

### ISSUE THREAD

**Issue by mattwritescode** [xamarin/Essentials#485]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
When using 0.9.1 Xamarin Essentials on a library I created that uses SecureStorage, the app will crash whenever the SecureStorage code is run with the following error message "Device doesn't support secure storage with current settings. Please add Keychain entitlement for iOS.".

### Steps to Reproduce

1. Create Xamarin.Forms library and incorporate Xamarin.Essentials to use SecureStorage.
2. Build library into NuGet package.
3. Add NuGet package to new Xamarin project.
4. Enable the Keychain entitlement and add a keychain access group for the application's bundle identifier.
5. Open the Entitlements.plist in the iOS target and find the Keychain entitlement and enable it. This will automatically add the application's identifier as a group.
6. In the project properties, under iOS Bundle Signing set the Custom Entitlements to Entitlements.plist.
7. Run app and make sure to run the code that uses SecureStorage.
8. App will crash. Error output attached as a file.

### Expected Behavior
SecureStorage will work without crashing when entitlements are correctly set up.

### Actual Behavior
SecureStorage code crashes app consistently.

### Basic Information

- Version with issue: 0.9.1
- Last known good version:
- IDE: Visual Studio Community for Mac
- Platform Target Frameworks: 
  - iOS:  11.4
  - Android: API 25.
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin Essentials, Xamarin.Forms
- Affected Devices: Simulator and all iOS Devices.

[SecureStorageError.txt](https://github.com/xamarin/Essentials/files/2308145/SecureStorageError.txt)

**Comment by jamesmontemagno** [comment]
You only need entitlements for the simulator. You do not need them for devices themselves. You can check our samples and it is working there for me.

**Comment by jamesmontemagno** [comment]
Looking at your error message we do not  output this error message at all. It is not in our source code at all. Can you supply a sample project.

**Comment by jamesmontemagno** [comment]
Will take a look, you can always delete the obj/bin in all the subfolders. This will make it really small :)

**Comment by mattwritescode** [comment]
[KeychainIssueSample.zip](https://github.com/xamarin/Essentials/files/2311523/KeychainIssueSample.zip)
Good tip. Didn't know that. There ya go.

**Comment by jamesmontemagno** [comment]
Ah, yes your issue here is that you didn't install Xamarin.Essentials into your iOS and Android applications. You only have the .net standard library that doesn't have any implementation in it.

**Comment by mattwritescode** [comment]
@jamesmontemagno I'm confused. The NuGet library has Xamarin.Essentials as a dependency already, why would the test project need to pull Xamarin.Essentials in as well? Also, even if I try to pull in Xamarin.Essentials to the test project for iOS and Xamarin.Forms, it still doesn't work for me and gives the same error as before:
<img width="502" alt="screen shot 2018-08-22 at 1 36 02 pm" src="https://user-images.githubusercontent.com/4481604/44483315-5de86900-a610-11e8-8130-7003e1025d4f.png">


On Android, it conflicts with the Xamarin.Android libraries and doesn't install: 
[Xamarin.EssentialsAndroidError.txt](https://github.com/xamarin/Essentials/files/2311590/Xamarin.EssentialsAndroidError.txt)

Maybe I'm missing something obvious here. If you can get my sample project to run, please save it and send it back to me. That would be super helpful.

**Comment by jamesmontemagno** [comment]
Will do. give me a few minutes.

**Comment by jamesmontemagno** [comment]
One thing I did was ensure Xamarin.Essentials was installed in all of your apps and .net standard libraries. It is required to have the Xamarin.Essentials in your app projects because that is where the platform specific code lives. The .NET Standard version is just a high level interface and will throw an exception if you don't install it into your other projects.

I also updated the Support libraries to 27.0.2.1.

It is also required to set this in your main activity in your Android app: 
            Xamarin.Essentials.Platform.Init(this, bundle); 

See: https://docs.microsoft.com/en-us/xamarin/essentials/get-started

Also be aware when you call .Result on a task that may lock your user interface. You will want to use a Task<string> and avoid using a void when doing async/await: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/

My recommendation is to try/catch specific exception and output the error message like I did to help diagnose the errors. Catching and not doing anything looses the full stack trace. 

One of your key area's was this:
foreach (KeyValuePair<string, string> entry in dict)

When i displayed your actual exception the cast here is not valid. You can use: DictionaryEntry  and then tostring on each object, but really, you could use Dictionary<string,string>

[SecureStorageBugTest.zip](https://github.com/xamarin/Essentials/files/2311687/SecureStorageBugTest.zip)

**Comment by mattwritescode** [comment]
Wow, several basic issues there. Thanks so much for the guidance!

**Comment by marwalsch** [comment]
@jamesmontemagno I am having the same issue using the library through an Uno Platform project (receiving `[0:] Error adding record: MissingEntitlement` upon storager interaction). Troubleshooting was unsuccessful thus far. Should I open a new issue or is this better to be directed to the Uno Platform directly?
