### ISSUE TITLE
Toast API

### ISSUE THREAD

**Issue by hbraasch** [xamarin/Essentials#516]
Please considering adding a cross platform Toast API.
Suggested specs:
The displayed toast shall appear fleetingly at bottom of screen and NOT be implemented using local notifications.
The display period shall be in seconds.
The text shall auto wrap.
The text shall CR at newlines

**Comment by gsmental** [comment]
there sample 

https://github.com/EgorBo/Toasts.Forms.Plugin

**Comment by hbraasch** [comment]
Thanks!!

 

However, the idea is not to have to use another plugin. The recommendation was to add a similar component to the Essentials plugin.

 

Cheers and thanks again.

**Comment by Redth** [comment]
Appreciate the input, and apologies that we don't yet have a great spot of what the 'spirit' of the project is and why this isn't a good fit.

I've started a PR to add some more information to the contribution guide: https://github.com/xamarin/Essentials/pull/585

Basically, this falls into the category of requiring somewhat extensive custom UI code to make happen on platforms other than Android.  This might make more sense in Xamarin.Forms or some UI library.  Xamarin.Essentials avoids UI whenever possible, and the only real instances we allow any UI related code at all is really around when the platforms themselves provide a UI already.  If you see #518 this is more likely to be included because it leverages UI bits that each platform already uses for displaying notifications, and therefore doesn't require custom UI.

Thanks for the suggestion, but we're not going to consider implementing it at this point in time.  Sorry!
