### ISSUE TITLE
Phone Dialer Immediate Call

### ISSUE THREAD

**Issue by TonyLugg** [xamarin/Essentials#535]
Is it possible to make the phone dialer dial the number immediately without having to touch the call button?

**Comment by jamesmontemagno** [comment]
So, it would be available in Android, but not in iOS or UWP or any other platform that I know. Additionally, on Android it requires additional permissions.

https://stackoverflow.com/questions/11699819/how-do-i-get-the-dialer-to-open-with-phone-number-displayed

Since it isn't a cross-platform API on a majority of the platforms we do not want to introduce additional overrides or properties at all for this.
