### ISSUE TITLE
Additional Platform Support

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#662]
With Xamarin.Essentials our priority on platform support is focused on iOS, Android, and UWP. We understand that there are many requests for additional platforms. Some are being investigated, some in development (by the Essentials team and some by community). We are going to use this as single place for platform support so we don't have a bunch of open issues.

* [x] iOS - Supported By Microsoft
* [x] Android - Supported By Microsoft
* [x] UWP - Supported By Microsoft
* [x] [macOS](https://github.com/xamarin/Essentials/pull/653)
* [ ] [WinForms/WPF](https://github.com/xamarin/Essentials/pull/1079)
* [ ] GTK#
* [x] [Tizen](https://github.com/xamarin/Essentials/pull/555) - Supported by Samsung
* [x] watchOS - Supported By Microsoft
* [x] tvOS - Supported By Microsoft
* [ ] .NET Core 
* [ ] Web Assembly

**Comment by AndreiMisiukevich** [comment]
Hi James @jamesmontemagno 
I'd like to see Connectivity and Clipboard support for Mac and Gtk
0.0) **Mac Clipboard** is already done by @mattleibow in his fork
0.1) **Mac connectivity** here is PR https://github.com/mattleibow/Essentials/pull/1

Where should I create PR for point 1
1.0) **Gtk Clipboard**
1.1) **Gtk Connectivity**

May i do it to this project or to anybody's fork?

Thx

**Comment by VladislavAntonyuk** [comment]
Since Xamarin Forms made Device.OpenUri obsolete, Xamarin Essentials should implement this feature for all platforms (macOS, WPF, GTK, etc)

**Comment by danielmeza** [comment]
Since GTK run in a variety of platforms principality not mobile like Linux and Windows, it result difficult to find the right way to start implement components specially in Linux platforms. @jamesmontemagno  there is perhaps a get started guide or research document to post here and give a path to the community in order to speed up the collaboration to this platform?

**Comment by JunielKatarn** [comment]
@danielmeza @jamesmontemagno 
I plan to invest some free time to make GTK# happen to add another supported platform to my Xamarin.Forms published app.

Can someone point me in the right direction?
I plan to develop using a Linux environment, and willing to work on the Xamarin.Forms potentially missing pieces.

**Comment by JunielKatarn** [comment]
> Where should I create PR for point 1
> 1.0) **Gtk Clipboard**
> 1.1) **Gtk Connectivity**

@AndreiMisiukevich as far as I know, no one is actively working on Gtk, but I'm very interested on this platform getting ported to.

I'm not experienced with Gtk development, but I'm willing to spend some time helping.
Do you have any partial work, or at least guidance?

**Comment by AndreiMisiukevich** [comment]
@JunielKatarn sorry, no, I don't.

**Comment by mattleibow** [comment]
@JunielKatarn GTK# will be AWESOME!

Just start with what you can and add as you go. Have a look at how the WPF PR is going: https://github.com/xamarin/Essentials/pull/1079 or even the merged macOS: https://github.com/xamarin/Essentials/pull/653

You might just get started by slowly adding the Xxx.gtk.cs for APIs that you support.

**Comment by knocte** [comment]
Hey guys with regards to GTK#/Linux support, FYI this would cover Connectivity:

https://github.com/xamarin/Essentials/pull/1239

And this would cover Clipboard support (sorry I didn't have time to create PR from this yet):

https://github.com/nblockchain/DotNetEssentials/commit/a5bb9b4902b5aeee0d43f0e121694774179cc11b

**Comment by danielmeza** [comment]
@knocte that can also cover WinForms/WPF

**Comment by knocte** [comment]
> that can also cover WinForms/WPF

Good point, that's why I named the PR ".NETStandard 2.0 Connectivity", not explicitly mentioning Linux.

**Comment by danielmeza** [comment]
What about iOS/Android with the implementation of .net 5?

**Comment by knocte** [comment]
I didn't look into that.

**Comment by knocte** [comment]
> Hey guys with regards to GTK#/Linux support, FYI this would cover Connectivity:

FYI #1239 has been superseded by https://github.com/xamarin/Essentials/pull/1291

> And this would cover Clipboard support (sorry I didn't have time to create PR from this yet):

PR was added now: https://github.com/xamarin/Essentials/pull/1290

**Comment by danielmeza** [comment]
Well now with MAUI, the GTK platform need to be a priority in order to bring full support to the Linux OS.

**Comment by knjump** [comment]
I'm trying to display video in a WPF project using xamarin and C#. In my attempt to figure out displaying video, I loaded the example [here](https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/MediaElementDemos) and was able to get it to work in an Android emulator.  I tried adding a WPF project using the directions [here](https://dev.to/krdmllr/setting-up-a-xamarin-forms-wpf-backend-on-net-core-109l), but was unable to display video.  I got the error `Xamarin.Essentials.NotImplementedInReferenceAssemblyException: 'This
 functionality is not implemented in the portable version of this assembly.     You 
should reference the NuGet package from your main application project in order to 
reference the platform-specific implementation.'`.  I asked a question on stackoverflow [here](https://stackoverflow.com/questions/66954780/video-wont-display-in-wpf-project-using-xamarin-forms?noredirect=1#comment118416986_66954780), and haven't found a solution. A commenter suggested that I post a comment here. 

Is there a workaround to display a video element under WPF?

**Comment by jfversluis** [comment]
I think it's safe to say at this point that we won't be making any big investments in adding new platforms anymore. Thanks everyone for your input here!

**Comment by JunielKatarn** [comment]
> 

What about macOS and GTK#?
Will those still be at least community supported?

**Comment by VladislavAntonyuk** [comment]
MacOS is supported using MacCatalyst.

but as for GTK# I am interested in. If it can be included in MAUI repo, so community can start contributing.

as for me, the problem with MAUI-Linux repo, that we still need somehow build and install workloads to make it work.
