### ISSUE TITLE
[IOS] Map.OpenAsync doesn't popup app selection 

### ISSUE THREAD

**Issue by robinlevelapp** [xamarin/Essentials#835]
### Description

when using Map.OpenAsync on IOS, it doesn't popup app selection even there are
other maps app installed (google maps, waze)

### Steps to Reproduce

1. install waze and/or google maps
2. execute Map.OpenAsync()

### Expected Behavior
should popup a app selection just like in android.

### Actual Behavior
Opens directly the plans (native ios map app)

### Basic Information

- Version with issue:  Xamarin Essential v1.1.0
- Last known good version:unknown
- IDE:VS2019
- Platform Target Frameworks: 
  - iOS:  12.10.0.157
- Nuget Packages:  Xamarin.Essentials
- Affected Devices: Tested on IPhone X

**Comment by Redth** [comment]
On iOS there's no real notion of a picker for which maps app to use since each maps app will have its own URL scheme and potentially different query string parameter names to specify direction information.  We'd have to maintain a list of other apps and check if they're installed and then decide some sort of custom UI to present the user for them to pick (could be an action sheet i suppose).

It's certainly possible to do this yourself with existing essentials and forms API's.  This is untested code but it might look something like this:

```csharp
const string GOOGLEMAPS = "comgooglemaps://";
const string WAZEMAPS = "waze://";

var mapApps = new [] { GOOGLEMAPS, WAZEMAPS };
var installedMapApps = new List<string>();

foreach (var a in mapApps) {
    if (await Launcher.CanOpenAsync(a))
        installedMapApps.Add(a);
}

var choice = await DisplayActionSheet ("Open Map in...", "Cancel", null, installedMapApps.ToArray());

if (choice == GOOGLEMAPS)
    await Launcher.OpenAsync($"{GOOGLEMAPS}?center={location.Latitude},{location.Longitude}";
} else if (choice == WAZEMAPS) {
    await Launcher.OpenAsync($"{WAZEMAPS}?l={location.Latitude},{location.Longitude}";
}
```

I'd like to see if there's interest from others before we decided whether or not to add this to the roadmap.

**Comment by jamesmontemagno** [comment]
That looks like a fun blog post for the Xamarin blog @redth :)

**Comment by jamesmontemagno** [comment]
Marking closed as we use the native APIs as much as possible on each platform and the Maps uses the native MapKit APIs to open the maps.
