### ISSUE TITLE
LaunchStore

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#860]
H

Please add LaunchStore to future release of Essentials 

This should launch the AppStore or Play Store with home page or to specific feature

Here are examples:

LaunchStore()

This will open the default store (AppStore for iOS and Play Store for Android and Microsoft Store for UWP) as per the device and it will go to home page

LaunchStore({app_id})

It will open the App home page (or company page) on the default store as per the device.

LaunchStore({app_id}, Rating.4)

If ossicle it will apply app rating directly to the default store, in above example I am giving 4 stars to the app.

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by jamesmontemagno** [comment]
Thanks for the suggestion. 

This can be accomplished via the launcher API, which is what my plugin: https://github.com/jamesmontemagno/StoreReviewPlugin does today. Since Android has many apps stores there is no real way to implement this well. It is best left up to developers on how to launch the correct app store for their application.
