### ISSUE TITLE
[Bug] Positioning of Share dialog in iPad iOS is top left instead of top right When using Xamarin.Essentials share feature

### ISSUE THREAD

**Issue by poliahrameshkumar** [xamarin/Essentials#944]
### Description
Share dialog in iPad iOS is positioned on top left instead of top right When using Xamarin.Essentials share feature.
### Steps to Reproduce

1. Follow the official link https://docs.microsoft.com/en-us/xamarin/essentials/share?tabs=ios to create share option in iOS iPad device
2. The share dialog is positioned in top left instead of top right

### Basic Information

- Version with issue: Xamarin.Essentials latest version
- Last known good version: No good version
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  13.0
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: xamarin.essentials
- Affected Devices: All iPads

**Comment by Redth** [comment]
It seems like this is because we are setting the SourceView to be effectively the entire view of the view controller: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Share/Share.ios.cs#L29

I guess this probably grabs 0,0 as the location, hence the top left.  Since we don't really know which view you want it appearing from, it's not really something we can infer.

We could allow a global static property to override the location I suppose, OR maybe we could add an overload which takes a Forms `View` and then on iOS we'd grab the native view and use that as the source.

@mattleibow @newky2k @jamesmontemagno any thoughts?

**Comment by poliahrameshkumar** [comment]
Could you guide me how to to achieve setting global static property or overload forms view?

**Comment by poliahrameshkumar** [comment]
@jamesmontemagno can you help me on how to bring share dialog on top right corner instead of top left corner on iPad?

**Comment by bobwhitten** [comment]
PR #980 will put the share popover at top-right, which would close this issue, I believe.

**Comment by mattleibow** [comment]
I got some comments here that may be useful to discuss: https://github.com/xamarin/Essentials/pull/980#issuecomment-554398486

**Comment by jamesmontemagno** [comment]
Fixed with https://github.com/xamarin/Essentials/pull/980
